/**
 * @file interrupts.c
 *
 * Interrupts is a general term that encompasses the following:
 * 
 *  IRQ: Hardware generated, asynchronous interrupts. These interrupts are
 *    generated by peripheral hardware devices (such as the keyboard) and
 *    sent to the kernel via the PIC.
 *    
 *  INT: Software Interrupts, synchronously generated by the INT instruction.
 *    Software Interrupts are most commonly used for system calls, which 
 *    allow users to communicate with and make requests of the kernel.
 *
 *  EXN: Exceptions are synchronous interrupts, generated by intructions
 *    that violate some hardware or kernel defined rule. The most common
 *    example of an exeption is divide-by-0. Other common exceptions 
 *    include Page Faults (which occur when accessing unmapped virtual pages),
 *    and General Protection Faults (which occur when an instruction attempts
 *    to perform an action outside of their priviledge level).
 *
 * @author David Matlack
 */
#include <kernel/interrupts.h>
#include <x86/pic.h>

int interrupts_init(void) {

  /*
   * Initialize the exception handlers by installing handlers in the 
   * IDT.
   */
  //TODO install exception handlers

  /*
   * Initialize hardware interrupts by first telling the PIC where in the IDT it 
   * can find its interrupts handlers, and then installing the necessary interrupts 
   * handlers for each device connected to the PIC.
   */
  pic_init(INTERRUPTS_IDT_PIC_MASTER_OFFSET, INTERRUPTS_IDT_PIC_SLAVE_OFFSET);
  //TODO install device handlers

  /*
   * Initialize the system calls by installing handlers in the IDT.
   */
  //TODO install system call handlers
}
